# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-CGI-Builder
version:      1.27
version_from: lib/Apache/CGI/Builder.pm
installdirs:  site
requires:
    CGI::Builder:                  1.2
    Class::props:                  1.62
    mod_perl:                      0
    Object::props:                 1.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
